### ISSUE TITLE
VMExtensionProvisioningError For SQL-AlwaysOn 2017

### ISSUE THREAD

**Issue by IhorLeontiev** [hansenms/iac#4] opened 2018-04-27 07:36 UTC
Deployment SQL-AlwaysOn failling with "VM has reported a failure when processing extension 'configuresql0'. Error message: \"DSC Configuration 'SQLServerPrepareDsc' completed with error(s). Following are the first few: PowerShell DSC resource MSFT_xCluster  failed to execute Set-TargetResource functionality with error message: The running command stopped because the preference variable \"ErrorActionPreference\" or common parameter is set to Stop: The IP Address '' is already used.  The SendConfigurationApply function did not succeed.\"."
I think that cluster is using wrong adress for configuration

**Comment by hansenms** [comment] 2018-04-27 15:06
I can't reproduce the problem. I just deployed the template. So the issue may well be that you have something already in the subnet you are deploying in with a conflicting IP address. The issue is that we need a dummy IP for the cluster, so if the cluster IP is 10.0.1.30, we also grab 10.0.1.31, it is calculated here:

https://github.com/hansenms/iac/blob/master/sql-alwayson/DSC/PrepareSQLServer.ps1#L35-L38

If this is not your issue, can you post steps to reproduce this issue. If I don't hear back in a few days, I will close this since I cannot reproduce based on current information.

**Comment by hansenms** [comment] 2018-05-02 14:33
Closing this there was no response.

**Closed as completed by hansenms** 2018-05-02 14:33 UTC
